#!/bin/sh

docker-scripts/docker_build_base buildarm64 "-DCMAKE_TOOLCHAIN_FILE=toolchains/linux_arm64.cmake"
docker-scripts/docker_build_base buildarm64 "-DRASPBERRY_PI_COMPILATION=TRUE -DCMAKE_TOOLCHAIN_FILE=toolchains/linux_arm64.cmake"
