#!/bin/sh

URL_TO_FILE=$1
ZIP_FILE=$2
SCRIPT_FILE_TO_EXECUTE=$3
FOLDER_TMP_FILES=${HOME}/tmp

rm -rf ${FOLDER_TMP_FILES}
mkdir -p ${FOLDER_TMP_FILES}
cd ${FOLDER_TMP_FILES}
wget ${URL_TO_FILE}/${ZIP_FILE}
unzip ${ZIP_FILE}
chmod +x ./${SCRIPT_FILE_TO_EXECUTE}
./${SCRIPT_FILE_TO_EXECUTE}
