#ifndef __HW_DEFS_HPP
#define __HW_DEFS_HPP

#define AUDIO_CHANNELS 2
#define SAMPLE_RATE 48000
#define PITCH_RATE (67027964 / ((float)SAMPLE_RATE * 2048))

#define TOP_WIDTH_3DS 400
#define BOT_WIDTH_3DS 320
#define HEIGHT_3DS 240

#define TOP_SPECIAL_DS_WIDTH_3DS 384
#define BOT_SPECIAL_DS_WIDTH_3DS 320

#define TOP_SCALED_DS_WIDTH_3DS 320
#define BOT_SCALED_DS_WIDTH_3DS 320

#define WIDTH_DS 256
#define HEIGHT_DS 192

#define WIDTH_GBA 240
#define HEIGHT_GBA 160

#define WIDTH_SCALED_GBA 360
#define HEIGHT_SCALED_GBA 240

#define WIDTH_GB 160
#define HEIGHT_GB 144

#define WIDTH_SCALED_GB 266
#define HEIGHT_SCALED_GB 240

#define WIDTH_SCALED_SNES 284
#define HEIGHT_SCALED_SNES 224

#define WIDTH_SNES 256
#define HEIGHT_SNES 224

#define WIDTH_NES 256
#define HEIGHT_NES 240

#define IN_VIDEO_WIDTH HEIGHT_3DS
#define IN_VIDEO_HEIGHT (TOP_WIDTH_3DS + BOT_WIDTH_3DS)
#define IN_VIDEO_SIZE (IN_VIDEO_WIDTH * IN_VIDEO_HEIGHT)

#define TOP_SIZE_3DS (TOP_WIDTH_3DS * HEIGHT_3DS)
#define IN_VIDEO_NO_BOTTOM_SIZE ((TOP_WIDTH_3DS - BOT_WIDTH_3DS) * HEIGHT_3DS)

#endif
