name: CD

on: ['push']

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2022,      os: windows-2022  }
        - { name: Linux GCC,           os: ubuntu-latest }
        - { name: macOS x64,           os: macos-13  }
        - { name: macOS Apple Silicon, os: macos-14  }
        config:
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      shell: bash
      run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install ${{matrix.platform.flags}} ${{matrix.config.flags}}

    - name: Build
      shell: bash
      run: cmake --build build --config Release

    - name: Pack
      shell: bash
      run: cd build && cpack -G ZIP

    - name: Archive resulting artifact
      uses: actions/upload-artifact@v3
      with:
        name: cc3dsfs_zip
        path: build/cc3dsfs*.zip

  publish:
    name: Publishing
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: cc3dsfs_zip
    - name: Auto-Release the zips
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly-latest"
        prerelease: true
        title: "Automatic Build"
        files: |
          cc3dsfs*.zip
